<div class="container">
    <div class="row">
        <div class="span12" style="margin-top: 20px">
            <legend class="title">
                <h3>Lista de Funcionalidades</h3>
            </legend>
            <div class="btn-toolbar">
                <a href="admin.php?r=funcionalidade/inserir">
                    <button class="btn btn-primary">+ Novo Funcionalidade</button>
                </a>
            </div>
            <div class="well">
                <table class="table table-hover">
                    <col style="width: 10%">
                    <thead>
                    <tr class="bold">
                        <th>#</th>
                        <th>Nome</th>
                        <th>Descrição</th>
                        <th>Ìcone</th>
                        <th style="width: 36px;">Ações</th>
                    </tr>
                    </thead>
                    <tbody>

                    <tr class="bold">
                        <td>@todo</td>
                        <td>@todo</td>
                        <td>@todo</td>
                        <td><img src="img/icon-calendar.png"
                                 width="30" height="30"></td>
                        <td style="width: 36px;">
                            <a href="admin.php?r=funcionalidade/editar&id=1"><i class="icon-edit"></i></a>
                            <a href="admin.php?r=funcionalidade/excluir&id=1"><i class="icon-remove"></i></a>
                        </td>
                    </tr>

                    <tr class="bold">
                        <td>@todo</td>
                        <td>@todo</td>
                        <td>@todo</td>
                        <td><img src="img/icon-calendar.png"
                                 width="30" height="30"></td>
                        <td style="width: 36px;">
                            <a href="admin.php?r=funcionalidade/editar&id=2"><i class="icon-edit"></i></a>
                            <a href="admin.php?r=funcionalidade/excluir&id=2"><i class="icon-remove"></i></a>
                        </td>
                    </tr>

                    <tr class="bold">
                        <td>@todo</td>
                        <td>@todo</td>
                        <td>@todo</td>
                        <td><img src="img/icon-calendar.png"
                                 width="30" height="30"></td>
                        <td style="width: 36px;">
                            <a href="admin.php?r=funcionalidade/editar&id=3"><i class="icon-edit"></i></a>
                            <a href="admin.php?r=funcionalidade/excluir&id=3"><i class="icon-remove"></i></a>
                        </td>
                    </tr>

                    <tbody>

                </table>
            </div>
        </div>
    </div>
</div>