<div class="container">
    <div class="row">
        <div class="span12" style="margin-top: 20px">

            <legend class="title">
                <h3>Lista de funcionarios</h3>
            </legend>

            <div class="btn-toolbar">
                <a href="admin.php?r=funcionario/inserir">
                    <button class="btn btn-primary">+ Novo funcionario</button>
                </a>
            </div>

            <div class="well">

                <table class="table table-hover">
                    <col style="width: 10%">
                    <thead>
                    <tr class="bold">
                        <th>#</th>
                        <th>Nome</th>
                        <th>Email</th>
                        <th>senha</th>
                        <th style="width: 36px;">Ações</th>
                    </tr>
                    </thead>
                    <tbody>

                        <tr class="bold">
                            <td>@todo</td>
                            <td>@todo</td>
                            <td>@todo</td>
                            <td>******</td>
                            <td style="width: 36px;">
                                <a href="admin.php?r=funcionario/editar&id=1"><i class="icon-edit"></i></a>
                                <a href="admin.php?r=funcionario/delete&id=1"><i class="icon-remove"></i></a>
                            </td>
                        </tr>

                        <tr class="bold">
                            <td>@todo</td>
                            <td>@todo</td>
                            <td>@todo</td>
                            <td>******</td>
                            <td style="width: 36px;">
                                <a href="admin.php?r=funcionario/editar&id=2"><i class="icon-edit"></i></a>
                                <a href="admin.php?r=funcionario/delete&id=2"><i class="icon-remove"></i></a>
                            </td>
                        </tr>

                        <tr class="bold">
                            <td>@todo</td>
                            <td>@todo</td>
                            <td>@todo</td>
                            <td>******</td>
                            <td style="width: 36px;">
                                <a href="admin.php?r=funcionario/editar&id=3"><i class="icon-edit"></i></a>
                                <a href="admin.php?r=funcionario/delete&id=3"><i class="icon-remove"></i></a>
                            </td>
                        </tr>

                    <tbody>
                </table>
            </div>
        </div>
    </div>
</div>
