<div class="container">
    <div class="row">
        <div class="span12" style="margin-top: 20px">
            <legend class="title">
                <h3>Lista de Mensagens</h3>
            </legend>

            <div class="well">
                <table width="100%" class="table">
                    <col style="width: 10%">
                    <thead>
                    <tr class="bold">
                        <td>#</td>
                        <td>Nome</td>
                        <td>E-mail</td>
                        <td>Assunto</td>
                        <td style="width: 36px;">Ações</td>
                    </tr>
                    </thead>
                    <tbody>

                    <tr class="bold">
                        <td>@todo</td>
                        <td>@todo</td>
                        <td>@todo</td>
                        <td>@todo</td>
                        <td style="width: 36px;">
                            <a href="admin.php?r=faleConosco/see&id=1"><i class="icon-eye-open"></i></a>
                            <a href="admin.php?r=faleConosco/delete&id=1"><i class="icon-remove"></i></a>
                        </td>
                    </tr>

                    <tr class="bold">
                        <td>@todo</td>
                        <td>@todo</td>
                        <td>@todo</td>
                        <td>@todo</td>
                        <td style="width: 36px;">
                            <a href="admin.php?r=faleConosco/see&id=2"><i class="icon-eye-open"></i></a>
                            <a href="admin.php?r=faleConosco/delete&id=2"><i class="icon-remove"></i></a>
                        </td>
                    </tr>

                    <tr class="bold">
                        <td>@todo</td>
                        <td>@todo</td>
                        <td>@todo</td>
                        <td>@todo</td>
                        <td style="width: 36px;">
                            <a href="admin.php?r=faleConosco/see&id=3"><i class="icon-eye-open"></i></a>
                            <a href="admin.php?r=faleConosco/delete&id=3"><i class="icon-remove"></i></a>
                        </td>
                    </tr>

                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>