<!doctype html>
<html dir="ltr" lang="pt-BR">
<head>
    <meta charset="utf-8">
    <title>Dexter Courier | Home</title>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>

    <!-- Le styles -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/bootstrap-responsive.css" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>
<body>

<header class="header">
    <div class="container">
        <a href="index.php" class="logo left">Dexter Courier</a>
        <nav class="right">
            <ul>
                <li>
                    <a href="index.php">HOME</a>
                </li>
                <li>
                    <a href="index.php?r=site/sobre">SOBRE</a>
                </li>
                <li>
                    <a href="index.php?r=site/servicos">SERVIÇOS</a>
                </li>
                <li>
                    <a href="index.php?r=site/contato">CONTATO</a>
                </li>
                <li>
                    <a href="index.php?r=site/cadastro">CADASTRE-SE</a>
                </li>
            </ul>
        </nav>
    </div>

</header>