<section class="banner">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

        <!-- Wrapper for slides -->

        <div class="carousel-inner">

            <div class="item active" style="background-image:url('img/banner.jpg')">
                <div class="container">
                    <div class="row">
                        <div class="span12">
                            <h2>Ipsum lorem dolor aliquam</h2>

                            <p>Accumsan orci faucibus id eu lorem semper. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna.</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="item" style="background-image:url('img/banner1.jpg')">
                <div class="container">
                    <div class="row">
                        <div class="span12">
                            <h2>Ipsum lorem dolor aliquam</h2>

                            <p>Accumsan orci faucibus id eu lorem semper. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna.</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="item" style="background-image:url('img/banner2.jpg')">
                <div class="container">
                    <div class="row">
                        <div class="span12">
                            <h2>Ipsum lorem dolor aliquam</h2>

                            <p>Accumsan orci faucibus id eu lorem semper. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna.</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="item" style="background-image:url('img/banner3.jpg')">
                <div class="container">
                    <div class="row">
                        <div class="span12">
                            <h2>Ipsum lorem dolor aliquam</h2>

                            <p>Accumsan orci faucibus id eu lorem semper. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna.</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="item" style="background-image:url('img/banner4.jpg')">
                <div class="container">
                    <div class="row">
                        <div class="span12">
                            <h2>Ipsum lorem dolor aliquam</h2>

                            <p>Accumsan orci faucibus id eu lorem semper. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna.</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>

    </div>
</section>

<section class="vantagens">
    <div class="title">
        <h1>Vantagens</h1>

        <h3>Uma plataforma moderna e flexivel para gerenciar a logistica do seu negócio.</h3>
    </div>

    <ul class="container">

        <li>
            <figure>
                <img src="img/icon-shop.png" alt="Sed ut perspiciatis">
                <figcaption>
                    <strong>Sed ut perspiciatis</strong>

                    <p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur</p>
                </figcaption>
            </figure>
        </li>

        <li>
            <figure>
                <img src="img/icon-flash.png" alt="Sed ut perspiciatis">
                <figcaption>
                    <strong>Sed ut perspiciatis</strong>

                    <p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur</p>
                </figcaption>
            </figure>
        </li>

        <li>
            <figure>
                <img src="img/icon-shop.png" alt="Sed ut perspiciatis">
                <figcaption>
                    <strong>Sed ut perspiciatis</strong>

                    <p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur</p>
                </figcaption>
            </figure>
        </li>

        <li>
            <figure>
                <img src="img/icon-flash.png" alt="Sed ut perspiciatis">
                <figcaption>
                    <strong>Sed ut perspiciatis</strong>

                    <p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur</p>
                </figcaption>
            </figure>
        </li>

    </ul>

    <div class="clear"></div>

    <a href="index.php?r=site/servicos" class="btn btn-flat">Veja mais Vantagens</a>
</section>

<section class="funcionalidades">
    <div class="title">
        <h1>Funcionalidades</h1>

        <h3>Uma plataforma moderna e flexivel para gerenciar a logistica do seu
            negócio</h3>
    </div>

    <ul class="container">

        <li>
            <figure>
                <img src="img/icon-calendar.png" alt="Vivamus ac erat vel erat">
                <figcaption>
                    <strong>Vivamus ac erat vel erat</strong>

                    <p>Fusce porta vitae ligula sit amet dapibus. Vivamus vitae tincidunt eros.</p>
                </figcaption>
            </figure>
        </li>

        <li>
            <figure>
                <img src="img/icon-cloud.png" alt="Vivamus ac erat vel erat">
                <figcaption>
                    <strong>Vivamus ac erat vel erat</strong>

                    <p>Fusce porta vitae ligula sit amet dapibus. Vivamus vitae tincidunt eros.</p>
                </figcaption>
            </figure>
        </li>

        <li>
            <figure>
                <img src="img/icon-support.png" alt="Vivamus ac erat vel erat">
                <figcaption>
                    <strong>Vivamus ac erat vel erat</strong>

                    <p>Fusce porta vitae ligula sit amet dapibus. Vivamus vitae tincidunt eros.</p>
                </figcaption>
            </figure>
        </li>

    </ul>
</section>

<section class="cadastro">
    <div class="container">
        <div class="left">
            <h3>Você cuida da sua empresa e nós da sua logistica.</h3>

            <p>Cadastre-se agora e tenha 20% de desconto no primeiro ano.</p>
        </div>
        <a href="index.php?r=site/cadastro" class="btn btn-flat right">Cadastre-se</a>
    </div>
</section>
