<footer class="footer">

    <ul>
        <li><a href="#" target="_blank"><img src="img/icon-fb.png" alt="Facebook"></a></li>
        <li><a href="#" target="_blank"><img src="img/icon-tw.png" alt="Twitter"></a></li>
        <li><a href="#" target="_blank"><img src="img/icon-gp.png" alt="Google+"></a></li>
        <li><a href="#" target="_blank"><img src="img/icon-fk.png" alt="Flickr"></a>
        </li>
    </ul>

    <div class="copy">&copy; 2014 Dexter Curier Logistica S/A.</div>

</footer>

<script src="js/jquery.min.js"></script>
<script src="js/bootstrap.js"></script>

<script type="text/javascript">
    $('.carousel').carousel({
        interval: 2000,
        pause: "false"
    });
</script>

</body>

</html>