<header class="header">
    <style type="text/css">
        textarea,
        input[type="text"],
        input[type="password"],
        input[type="datetime"],
        input[type="datetime-local"],
        input[type="date"],
        input[type="month"],
        input[type="time"],
        input[type="week"],
        input[type="number"],
        input[type="email"],
        input[type="url"],
        input[type="search"],
        input[type="tel"],
        input[type="color"],
        .uneditable-input {
            padding: 10px;
            height: auto;
        }
    </style>
</header>

<div class="container content">
    <div class="title center">
        <h1>Cadastre-se</h1>
    </div>

    <div class="banner-fixed">
        <img src="img/banner-cadastro.jpg" alt="Banner Sobre">
    </div>

    <!-- adicionado para exibir mensagens -->
    <?php if ( isset( $_SESSION[ 'mensagem' ][ 'valor' ] ) ): ?>
        <div class="alert alert-<?= isset( $_SESSION[ 'mensagem' ][ 'tipo' ] ) ? $_SESSION[ 'mensagem' ][ 'tipo' ] : '' ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                &times;
            </button>
            <?php echo isset( $_SESSION[ 'mensagem' ][ 'valor' ] ) ? $_SESSION[ 'mensagem' ][ 'valor' ] : '' ?>
        </div>
    <?php endif; ?>

    <form action="index.php?r=site/cadastro" method="post" class="form">
        <p>
            <label for="nome">Nome/Razao</label>
            <input type="text" name="nome_razao" id="nome_razao" required>
        </p>

        <p>
            <label for="nome">Nome/Razao</label>
            <input type="text" name="cpf_cnpj" id="cpf_cjpj" required>
        </p>

        <p>
            <label for="email">Email</label>
            <input type="email" name="email" id="email" required>
        </p>

        <p>
            <label for="tel">Telefone</label>
            <input type="tel" name="telefone" id="telefone">
        </p>

        <p>
            <button class="btn-default">Enviar</button>
        </p>
    </form>
</div>