<div class="container content">
    <div class="title center">
        <h1>Quem somos</h1>
    </div>

    <div class="banner-fixed">
        <img src="img/banner-sobre.jpg" alt="Banner Sobre">
    </div>

    <div class="column">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus,
            et, laboriosam eveniet qui a nobis omnis quibusdam facilis placeat
            ipsam voluptate consequuntur blanditiis reiciendis? Rerum, harum
            mollitia placeat deleniti vero.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi,
            ut, quo deleniti fugit illum repudiandae aperiam cupiditate quis
            aliquam eaque.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam,
            error, deserunt, temporibus, rerum facilis atque eligendi nesciunt
            deleniti unde iste officia placeat adipisci et eveniet voluptate
            reiciendis autem quo officiis.</p>
    </div>
    <div class="column">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus,
            et, laboriosam eveniet qui a nobis omnis quibusdam facilis placeat
            ipsam voluptate consequuntur blanditiis reiciendis? Rerum, harum
            mollitia placeat deleniti vero.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi,
            ut, quo deleniti fugit illum repudiandae aperiam cupiditate quis
            aliquam eaque.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam,
            error, deserunt, temporibus, rerum facilis atque eligendi nesciunt
            deleniti unde iste officia placeat adipisci et eveniet voluptate
            reiciendis autem quo officiis.</p>
    </div>

    <div class="videos">
        <h2>Vídeos</h2>

        <ul>
            <li><img src="http://lorempixel.com/350/200" alt=""></li>
            <li><img src="http://lorempixel.com/350/200" alt=""></li>
            <li><img src="http://lorempixel.com/350/200" alt=""></li>
            <li><img src="http://lorempixel.com/350/200" alt=""></li>
        </ul>
    </div>
</div>