<section class="servicos">
    <div class="container content">
        <div class="title center">
            <h1>Nossos Serviços</h1>

            <h3>Não importa o tamanho da sua empresa, a Dexter tem a solução
                certa para você.</h3>
        </div>
        <ul>
            <li>
                <a href="">
                    <img src="img/service-aereo.png" alt="Nulla sed egestas nulla">

                    <h2>Nulla sed egestas nulla</h2>

                    <p>Donec eget ultrices nisl, in cursus mauris. Mauris vitae erat vitae erat scelerisque posuere.</p>
                </a>
            </li>

            <li>
                <a href="">
                    <img src="img/service-calendar.png" alt="Nulla sed egestas nulla">

                    <h2>Nulla sed egestas nulla</h2>

                    <p>Donec eget ultrices nisl, in cursus mauris. Mauris vitae erat vitae erat scelerisque posuere.</p>
                </a>
            </li>

            <li>
                <a href="">
                    <img src="img/service-cargo.png" alt="Nulla sed egestas nulla">

                    <h2>Nulla sed egestas nulla</h2>

                    <p>Donec eget ultrices nisl, in cursus mauris. Mauris vitae erat vitae erat scelerisque posuere.</p>
                </a>
            </li>

            <li>
                <a href="">
                    <img src="img/service-fast.png" alt="Nulla sed egestas nulla">

                    <h2>Nulla sed egestas nulla</h2>

                    <p>Donec eget ultrices nisl, in cursus mauris. Mauris vitae erat vitae erat scelerisque posuere.</p>
                </a>
            </li>

            <li>
                <a href="">
                    <img src="img/service-loja.png" alt="Nulla sed egestas nulla">

                    <h2>Nulla sed egestas nulla</h2>

                    <p>Donec eget ultrices nisl, in cursus mauris. Mauris vitae erat vitae erat scelerisque posuere.</p>
                </a>
            </li>

            <li>
                <a href="">
                    <img src="img/service-money.png" alt="Nulla sed egestas nulla">

                    <h2>Nulla sed egestas nulla</h2>

                    <p>Donec eget ultrices nisl, in cursus mauris. Mauris vitae erat vitae erat scelerisque posuere.</p>
                </a>
            </li>
        </ul>
    </div>
</section>

<section class="mobile">
    <div class="container">
        <h2>A Dexter agora na sua mão</h2>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint,
            voluptas, veritatis earum quod saepe sed eaque tempore iure officia
            ea odit voluptatem minima blanditiis delectus illo ipsa ratione
            doloremque necessitatibus id veniam neque fugiat itaque ad magni
            repellat expedita non amet sequi dolores consequatur autem mollitia
            quaerat placeat harum cum.</p>
        <a href="#" class="btn btn-yellow">Android</a>
        <a href="#" class="btn btn-yellow">iPhone</a>
        <img src="img/iphone.jpg" alt="Dexter Mobile" class="phone">
    </div>
</section>