<style type="text/css">
textarea,input[type="text"],input[type="password"],input[type="datetime"],input[type="datetime-local"],input[type="date"],input[type="month"],input[type="time"],input[type="week"],input[type="number"],input[type="email"],input[type="url"],input[type="search"],input[type="tel"],input[type="color"],.uneditable-input
	{
	padding: 10px;
	height: auto;
}

.image-banner{
    background-image: url("img/banner/banner.jpg");
    background-position:center;
	background-repeat:no-repeat;
	width:1300;
	height:450;
	margin-left:10px;
}
</style>
</header>
<div class="image-banner">
<!-- To Do: Melhorar esta Pagina -->
</div>