<header class="header">
<!doctype html>
<html dir="ltr" lang="pt-BR">
<head>
<meta charset="utf-8">
<title>Dexter Courier | Admin</title>
<link href='http://fonts.googleapis.com/css?family=Raleway:400,700'
	rel='stylesheet' type='text/css'>
<link
	href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700'
	rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="css/style.css">
<!-- Le styles -->
<link href="css/bootstrap.css" rel="stylesheet">
<link href="css/bootstrap-responsive.css" rel="stylesheet">
<script src="js/jquery.min.js"></script>
<script src="js/bootstrap.js"></script>
<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
</head>
<body>
	<div class="container">
		<a href="index.php" class="logo left">Dexter Courier</a>
		<div class="btn-group pull-right">
			<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
			    <i class="icon-user"></i>
				<span class="caret"></span>
			</a>
			<ul class="dropdown-menu">
				<li><a href="#"><i class="icon-wrench"></i> Opções</a></li>
				<li class="divider"></li>
				<li><a href="admin.php?modulo=admin&controller=funcionarios&action=logout"><i class="icon-share"></i> Logout</a></li>
			</ul>
		</div>
		<nav class="right" style="margin: 8px 16px 0 0">
			<ul>
			 <li>
			     <a href="index.php?r=/">HOME</a>
			 </li>
			 <li>
			     <a href="admin.php?r=cliente/index">CLIENTES</a>
			 </li>
			 <li>
			     <a href="admin.php?r=faleConosco/index">MENSAGENS</a>
			 </li>
			 <li>
			     <a href="admin.php?r=funcionalidade/index">FUNCIONALIDADES</a>
			 </li>
			 <li>
			     <a href="admin.php?r=servico/index">SERVIÇOS</a>
			 </li>
			 <li>
			     <a href="admin.php?r=funcionario/index">FUNCIONARIOS</a>
			 </li>
		</ul>
		</nav>
	</div>
</header>